// src/app/layout.tsx

import "./globals.css";
import { Inter } from "next/font/google";
import Gnb from "../components/common/Gnb"; // Gnb 임포트 유지

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo List App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Gnb />{" "}
        {/* Gnb 컴포넌트를 레이아웃의 최상단에 렌더링. 이제 onAddTask 프롭스 필요 없음. */}
        {children}
      </body>
    </html>
  );
}
